<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
</head>
<body>
	<div class="container mt-5">
		<div id="profile">
			<div class="form-floating mb-3">
				<input type="text" class="form-control" id="name" placeholder="Enter name" name="name" value="mar">
				<label for="name">Enter name</label>
			</div>
			<div class="form-floating mb-3">
				<input type="text" class="form-control" id="surname" placeholder="Enter surname" name="surname" value="zal">
				<label for="surname">Enter surname</label>
			</div>
			<div class="form-floating mb-3">
				<select class="form-select" id="floatingSelect" aria-label="Floating label select example" name="city">
					<option disabled>Open this select menu</option>
					<option value="1" selected>Vilnius</option>
					<option value="2">Kaunas</option>
					<option value="3">Klaipėda</option>
				</select>
				<label for="floatingSelect">Select City</label>
			</div>
			<div class="btn-group btn-group-lg d-flex mb-3" role="group" aria-label="Basic checkbox toggle button group">
				<input type="checkbox" class="btn-check" id="btncheck1" autocomplete="off" name="lang[]" value="PHP">
				<label class="btn btn-outline-primary" for="btncheck1">PHP</label>

				<input type="checkbox" class="btn-check" id="btncheck2" autocomplete="off" name="lang[]" value="JS">
				<label class="btn btn-outline-warning" for="btncheck2">JS</label>

				<input type="checkbox" class="btn-check" id="btncheck3" autocomplete="off" name="lang[]" value="C++">
				<label class="btn btn-outline-info" for="btncheck3">C++</label>
			</div>
			<div class="form-floating mb-3">
				<textarea class="form-control" placeholder="Leave a comment here" id="floatingTextarea" name="comment">noriu mokintis programuoti :))</textarea>
				<label for="floatingTextarea">Comments</label>
			</div>
			<div class="mb-3">
				<input class="form-control form-control-lg" type="file" name="photo">
			</div>
			<div class="d-grid gap-2">
				<button class="btn btn-info btn-block" id="submit-ajax-FormData">Submit AJAX FormData</button>
			</div>
		</div>
	</div>
	<script src="assets/js/app.js"></script>
</body>
</html>