
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title><?=env('APP_NAME', 'Coutching');?></title>
    <link rel="stylesheet" href="./resources/css/main.css">
    <link rel="stylesheet" href="./resources/css/list.css">
    <link rel="stylesheet" href="./resources/css/navigation.css">  
</head>
<body>
    <header>
        <div id="header">
        <?php echo "{$user['first_name']} .:. {$user_id} .:. {$user['email']}"; ?>
        </div>
    </header>

    <main>
        <section>
            <?php
                if (isset($_GET['error'])) {
                    echo  $_GET['error'];
                }?>
        </section>
        <section>
            <?=getQuestionsList($page, $user_id);?>
        </section>
    </main>
    <footer>
        <div id="footer">
            <?=$footer;?>
        </div>
        
    </footer>
</body>
</html>